spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to MurthyDace accounts related production Related APIs "
  contactDetails:
    name: "Ravi - Product Owner lead"
    email: "Ravi@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
