Spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "3.0"

loans:
  message: "Welcome to MurthyDace loans related QA APIs "
  contactDetails:
    name: "Arun - QA Developer"
    email: "arun@murthydace.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345